<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">

	<!-- temporary -->
	<meta name="robots" content="noindex,nofollow">

        <?php echo $this->headTitle($this->translate('example.net'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

	<link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic|Bitter:700' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Rochester' rel='stylesheet' type='text/css'>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
    </head>
    <body>

        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"> &nbsp;<?php echo $this->translate('example.net') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li<?php if ($this->routeName()=='home') {?> class="active"<?php } ?>><a href="<?php echo $this->url('home') ?>"><span><span class="glyphicon glyphicon-home" aria-hidden="true"></span><?php echo $this->translate('Home') ?></span></a></li>
                    </ul>
		    <?php if ($this->userIsLogged()) { ?>
                    <ul class="nav navbar-nav">
                        <li<?php if ($this->routeName()=='profile') {?> class="active"<?php } ?>><a href="<?php echo $this->url('profile') ?>"><span><span class="glyphicon glyphicon-user" aria-hidden="true"></span><?php echo $this->translate('Profile') ?></span></a></li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li<?php if ($this->routeName()=='logout') {?> class="active"<?php } ?>><a href="<?php echo $this->url('logout') ?>"><span><span class="glyphicon glyphicon-off" aria-hidden="true"></span><?php echo $this->translate('Logout') ?></span></a></li>
                    </ul>
		    <?php } else { ?>
                    <ul class="nav navbar-nav">
                        <li<?php if ($this->routeName()=='login') {?> class="active"<?php } ?>><a href="<?php echo $this->url('login') ?>"><span><span class="glyphicon glyphicon-lock" aria-hidden="true"></span><?php echo $this->translate('Login') ?></span></a></li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li<?php if ($this->routeName()=='register') {?> class="active"<?php } ?>><a href="<?php echo $this->url('register') ?>"><span><span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span><?php echo $this->translate('Register') ?></span></a></li>
                    </ul>
		    <?php } ?>
                    <ul class="nav navbar-nav">
                        <li<?php if ($this->routeName()=='contact') {?> class="active"<?php } ?>><a href="<?php echo $this->url('contact') ?>"><span><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span><?php echo $this->translate('Contact') ?></span></a></li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li<?php if ($this->routeName()=='news') {?> class="active"<?php } ?>><a href="<?php echo $this->url('news') ?>"><span><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span><?php echo $this->translate('News') ?></span></a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
	    <div class="row">&nbsp;</div>
	    <div class="row">&nbsp;</div>
            <?php echo $this->content; ?>
	    <div class="row">&nbsp;</div>
	    <div class="row">&nbsp;</div>
        </div> <!-- /container -->

            <footer>
                <p>
			&copy; 2014 - <?php echo date('Y') ?> <?php echo $this->translate('All rights reserved.') ?>
		</p>
            </footer>

        <?php echo $this->inlineScript() ?>

    </body>
</html>
