<h1><?php echo $this->translate('Reset password'); ?></h1>
<hr/>
<br/>

<div class="container">

<?php
if ($this->form) {
$form = $this->form;
$form->setAttribute('action', $this->url('forgotpwd'))->prepare();
echo $this->form()->openTag($form);
echo $this->form()->render($form);
echo $this->form()->closeTag($form);
}
if ($this->email) {
echo sprintf($this->translate('forgotpwd_email_sent'),$this->email);
}
?>
</div>
